# xDefault values for speedDb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

mysql:
  auth:
    createDatabase: false
    rootPassword: password
