# Default values for monitoring 
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1


prometheus:
  server:
    global:
      scrape_interval: 15s

  extraScrapeConfigs: |
    - job_name: mysql
      static_configs:
        - targets:
          - prometheus-prometheus-mysql-exporter:9104
      relabel_configs:
        - source_labels: [__address__]
          target_label: instance


prometheus-mysql-exporter:
  annotations:
    mysql.exporter: "true"

  mysql:
    host: "speed-api-mysql-0.speed-api-mysql.speed"
    user: "root"
    pass: "password"
