apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: infra 
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/ingress
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
      - values-{{ .Values.env }}.yaml
